"""Prometheus metrics for chunk planning."""

from __future__ import annotations

from prometheus_client import Counter, Histogram

CHUNK_PLANNER_LATENCY_SECONDS = Histogram(
    "sec_chunk_planner_latency_seconds",
    "Latency to generate Groq chunk plans",
)

CHUNK_PLANNER_CHUNKS_TOTAL = Counter(
    "sec_chunk_planner_chunks_total",
    "Number of chunk jobs generated by planner",
    ["form_type"],
)
